{
 "title": "Custom metrics with mysql db",
 "time": { "from": "2021-12-21T08:21:30.047Z", "to": "2021-12-21T14:21:30.047Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Login Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select mtype from metrics where mname=\"Login\";"
    }
   ]
  },
  {
   "title": "Successful Login Request",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select mtype from metrics where mname=\"Successful\";"
    }
   ]
  },
  {
   "title": "Failed Login Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select mtype from metrics where mname=\"Failed\";"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "rawSql": "select * from metrics;\n" }
   ]
  }
 ]
}