apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: python
  namespace: custom-metrics
spec:
  template:
    spec:
      containers:
        - env:
            - name: MY_USER
              value: root
            - name: MY_PASS
              value: root
            - name: MY_HOST
              value: 172.30.214.169
            - name: MY_PORT
              value: '3306'
            - name: MY_DB
              value: custmet
          image: 'tvkrishna21/python-login-app-with-exp:1.1.3'
          name: python-app
          ports:
            - containerPort: 5000
              protocol: TCP